### ISSUE TITLE
Chat groups

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#19]

**Comment by AnthyG** [comment]
This should follow #6 !

**Comment by Plasmmer** [comment]
You can create milestones in order to organize issues' priorities.

**Comment by AnthyG** [comment]
I will probably have to improve the code for the private chat..
though both would basically use the same functions (except that group chat won’t use ecies to encrypt, because that would be bad for big groups, so just AES)

I should probably also extract some code-parts from lobby- and private-chat, to shorten the code, because for private-chat I just copied all of the lobby-chat parts and just edited them to fit private chats, which is somewhat a bad habit of mine.

So I will re-write the `addMessage`-function to work for all things, which will require some time.

Also see the following link for some differences between private chat and lobby chat
https://www.diffchecker.com/5mjB8rtG

**Comment by Plasmmer** [comment]
@AnthyG the chat groups will have options to be public or password-protected?

**Comment by AnthyG** [comment]
@Plasmmer there could be something like a index for public groups, but as anybody could theoretically just create a new group by changing the URL, so I'm not sure if the first person in a group should even be logged (so it that would be the group-"admin"), because it would just take up extra storage.
The "password-protection" of a group is the group's ID, which _can_ be quite long, if you want to enter it into the address bar :laughing:

So no, and somewhat-yes.

**Comment by AnthyG** [comment]
The branch for this is located at https://github.com/AnthyG/ThunderWave/tree/Group-Chat

**Comment by AnthyG** [comment]
Added basic functionality with commit e6ba8f70b2465ae7c542d3c9542881bd9fdc7e50!
You can now try a link like this: http://127.0.0.1:43110/thunderwave.bit/?GC:Abcdefghijklmnopqrstuvwxyz

**Comment by AnthyG** [comment]
Next up is to “merge” the mostly similar functions from lobby, private, and group chat together, to reduce the code-size, and to make it more “modular”

**Comment by AnthyG** [comment]
I will close this issue, and create some for already found bugs in group chat, as this was just for the basic implementation for groups.

**Comment by AnthyG** [comment]
Merging the functions as noted in https://github.com/AnthyG/ThunderWave/issues/19#issuecomment-348778123 is being worked on in ThunderWave Beta. For more information, see #106.

**Comment by DaniellMesquita** [comment]
@AnthyG you can use Bitcoin addresses in the groups, so who have the privatekey is owner of a group.
Or a system where owner can add other admins/roles.

**Comment by AnthyG** [comment]
@DaniellMesquita I think that should be a new issue.

**Comment by AnthyG** [comment]
Actually, I'm not sure how I would implement that 😆
Because I can't just use the public key of a user to create a group,.. everybody knows that key.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/AnthyG/ThunderWave/issues/116.
