### ISSUE TITLE
Can change message's color (background/text)

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#3]

**Comment by AnthyG** [comment]
This might be a bit hard, as almost every element would have to get styled dynamically, according to the colors the user selected. 😞

**Comment by Plasmmer** [comment]
Yes. Like is registered the contents to the messages, it can register the user customization options.

**Comment by AnthyG** [comment]
Closed with #28.

**Comment by Plasmmer** [comment]
@AnthyG user can set a custom color for a message?

**Comment by AnthyG** [comment]
Yes, you can toggle the dark theme in the settings.

Or did you mean something different?!?

**Comment by Plasmmer** [comment]
I talk about users changing the color of a message they want.
User can set a different color for each message.
Then, the site registers the balloon-color together the message.

**Comment by AnthyG** [comment]
Is this really necessary!?
I mean, why/ for what would you want to do that?

**Comment by Plasmmer** [comment]
If the programmers would think like this, today the Facebook Messenger would not have the function to apply a color to a friend in chat.

**Comment by AnthyG** [comment]
Applying a color to a friend is completely different from applying a color to _one specific_ message.

I just don't see why anyone would need something like this, and if you don't give any good purpose, I won't really even think about it. It's just a waste of my time to implement such a feature, but if you really really need it, make a fork, implement it yourself, and then do a pull-request.
Though, even then I'm unsure if I would even merge it, because as of now, I just don't see any sense in it. It just takes up extra space..
