### ISSUE TITLE
Store settings in the json file permanently

### ISSUE THREAD

**Issue by nipos** [AnthyG/ThunderWave#93]
Some browsers seem to have an issue with storing the chat settings permanently.
It would have many advantages if they were stored in the json file where the avatar settings are already stored.
They didn't get lost when I restarted my computer.
Additional advantages:
- It will sync between all browsers when they're accessing the same ZeroNet instance
- An graphical avatar setting could be implemented very easy

**Comment by AnthyG** [comment]
Wow, I have to admit, I'm a bit baffled by how hard this actually is...
I mean, my options-system might not be the best and blablabla, but it's good IMO.
To pretty much re-write it around a different API seems to be even harder (I mean, I actually have to write my own one, because I can't just say "save this in there, at that position").

I'm not sure, if I even want to publish the branch I made for it to at least be on a bit of a secure side, because the code-re-writing is just plain sh*t (and no, it doesn't yet work, because I have to probably re-think a bit more......)

😥

**Comment by AnthyG** [comment]
This has been added with pull-request https://github.com/AnthyG/ThunderWave/pull/96
